### ISSUE TITLE
设置字符集为英文字母时，验证容易报错

### ISSUE THREAD

**Issue by fqw123** [wenlng/go-captcha#12]
1. 设置英文字符集

chars := "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

 _ = capt.SetRangChars(strings.Split(chars, ""))

capt = captcha.GetCaptcha()

dots, b64, tb64, key, err := capt.Generate()

2. 前端点选结果

 {"dot":"110,198,48,88,197,72","key":"c39190357e6e59043729c59a8fa99a71"}
![image](https://github.com/wenlng/go-captcha/assets/43577558/bc0d57df-bc66-4584-afe6-ba5b9d937902)

3. 实际点选结果
{"0":{"Index":0,"Dx":105,"Dy":227,"Size":38,"Width":38,"Height":38,"Text":"N","Angle":330,"Color":"#fcb08e","Color2":"#6e3700"},"1":{"Index":1,"Dx":50,"Dy":111,"Size":31,"Width":31,"Height":31,"Text":"A","Angle":20,"Color":"#60c1ff","Color2":"#6e3700"},"2":{"Index":2,"Dx":193,"Dy":96,"Size":37,"Width":37,"Height":37,"Text":"F","Angle":325,"Color":"#b4fed4","Color2":"#660033"}}

期望和汉字的验证效果一致

**Comment by wenlng** [comment]
> 1. 设置英文字符集
> 
> chars := "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
> 
> _ = capt.SetRangChars(strings.Split(chars, ""))
> 
> capt = captcha.GetCaptcha()
> 
> dots, b64, tb64, key, err := capt.Generate()
> 
> 2. 前端点选结果
> 
> {"dot":"110,198,48,88,197,72","key":"c39190357e6e59043729c59a8fa99a71"} ![image](https://private-user-images.githubusercontent.com/43577558/266994221-bc0d57df-bc66-4584-afe6-ba5b9d937902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDM0NzgsIm5iZiI6MTcxNjA0MzE3OCwicGF0aCI6Ii80MzU3NzU1OC8yNjY5OTQyMjEtYmMwZDU3ZGYtYmM2Ni00NTg0LWFmZTYtYmE1YjlkOTM3OTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE0MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNDhhOGMzMmJhOGFjNDg2N2E1MGQxM2QyZjg4MzBjZDNmYTgwNTQ1NDA2MGQ5YTRmN2MzZTJmMmM1OWU2OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5GPIlJDS4qoBmPk8_hpim4xBRdBFhHLSq-gSMlBAvbM)
> 
> 3. 实际点选结果
>    {"0":{"Index":0,"Dx":105,"Dy":227,"Size":38,"Width":38,"Height":38,"Text":"N","Angle":330,"Color":"#fcb08e","Color2":"#6e3700"},"1":{"Index":1,"Dx":50,"Dy":111,"Size":31,"Width":31,"Height":31,"Text":"A","Angle":20,"Color":"#60c1ff","Color2":"#6e3700"},"2":{"Index":2,"Dx":193,"Dy":96,"Size":37,"Width":37,"Height":37,"Text":"F","Angle":325,"Color":"#b4fed4","Color2":"#660033"}}
> 
> 期望和汉字的验证效果一致

嘿嘿，v2 的位置计算将更精准了，即将发布，可关注一下！
