### ISSUE TITLE
There is a problem with the order of return variables in the comment

### ISSUE THREAD

**Issue by kk0x03** [wenlng/go-captcha#13]
// Generate is a function
/**
 * @Description: 			根据设置的尺寸生成验证码图片
 * @return CaptchaCharDot	位置信息
 * @return string			主图Base64
 * @return string			验证码KEY
 * @return string			缩略图Base64
 * @return error
 */
func (cc *Captcha) Generate() (map[int]CharDot, string, string, string, error) {
	dots, ib64, tb64, key, err := cc.GenerateWithSize(cc.config.imageSize, cc.config.thumbnailSize)
	return dots, ib64, tb64, key, err
}

There may be misunderstandings about the first use.

**Comment by wenlng** [comment]
> There may be misunderstandings about the first use.

The v2 version will be released soon, which is easier to use and can be followed.
