### ISSUE TITLE
是否考虑进一步加强校验？

### ISSUE THREAD

**Issue by zxdstyle** [wenlng/go-captcha#19]
目前支持的几个校验方式都是只校验最终结果，是否考虑加入用户行为校验？比如说拖动的速度、鼠标移动轨迹等等

**Comment by wenlng** [comment]
> 目前支持的几个校验方式都是只校验最终结果，是否考虑加入用户行为校验？比如说拖动的速度、鼠标移动轨迹等等

你好，感谢提议，在下一个阶段才有计划扩展增加行为的变速运动、轨迹（贝塞尔曲线算法）等校验算法，目前V2版本还处于第一阶段，像移动端APP的依赖包等等还需要完善哈
