### ISSUE TITLE
react 滑动验证失败后 无法手动刷新~~~ 导致滑块不能恢复到最左侧初始位置 

### ISSUE THREAD

**Issue by playerlife** [wenlng/go-captcha#24]
react 滑动验证失败后 无法手动刷新~~~ 导致滑块不能恢复到最左侧初始位置 

能不能放开自动刷新的api

**Comment by wenlng** [comment]
在 v2.0.3 版本已加了组件导出方法如  refresh()、reset()、clear() 等，支持组件调用，如：
`
 <gocaptcha-xxx ref="domRef"/>
domRef.value.refresh() 
`
https://github.com/wenlng/go-captcha-vue/tree/v2.0.3
