### ISSUE TITLE
服务端要保存什么数值来判断前端传来的point位置准确？

### ISSUE THREAD

**Issue by aa12gq** [wenlng/go-captcha#25]
服务端要保存什么数值来判断前端传来的point位置准确？
 服务端是保存主图空缺贴图的坐标吗，那么这个坐标是怎么得到的啊，tilex和tiley是用来给小图的初始位置吧

**Comment by wenlng** [comment]
参考一下实例：https://github.com/wenlng/go-captcha-example/blob/5baa8921ba30dac24e9de77fc1ac87d579a93020/internal/logic/captdata/slide_region.go#L60
将验证码的 xxx.GetData() 的信息在服务端保存，用于前端传递的 point 参考校验
