### ISSUE TITLE
期望提供原生JS的使用方式

### ISSUE THREAD

**Issue by admpub** [wenlng/go-captcha#27]
如题，我看目前提供的几种使用方式都是依赖各种JS框架，所以不使用框架的情况无法使用。期望能够提供原生JS的引用支持

**Comment by wenlng** [comment]
哈喽，目前请参考一下JS原生的实例：https://github.com/wenlng/go-captcha-example/tree/v2/web/native
后面我会将这个编写成原生 jslib 形式

**Comment by admpub** [comment]
> 哈喽，目前请参考一下JS原生的实例：https://github.com/wenlng/go-captcha-example/tree/v2/web/native
> 
> 后面我会将这个编写成原生 jslib 形式

我刚刚正是看见了这个仓库里native部分的例子故而关闭了此issue，感谢作者的付出，非常棒的开源项目，我的nging项目打算使用它😄
