### ISSUE TITLE
是否考虑加入更多验证方式

### ISSUE THREAD

**Issue by D0n9** [wenlng/go-captcha#4]
查看 Demo 好像只支持「选择文字」验证方式，请问是否考虑加入诸如「滑动验证」「旋转验证」等验证方式。

**Comment by wenlng** [comment]
> 查看 Demo 好像只支持「选择文字」验证方式，请问是否考虑加入诸如「滑动验证」「旋转验证」等验证方式。

你好，已经在规划“滑动式”、“旋转式”、“图形式”等多种方式验证模块的支持了

**Comment by caifenglin** [comment]
图片文字能否支持内嵌文件方式

**Comment by wenlng** [comment]
> 图片文字能否支持内嵌文件方式

v2 已支持，即将发布
