### ISSUE TITLE
我做了一个Angular版本的示例代码

### ISSUE THREAD

**Issue by wikylyu** [wenlng/go-captcha#6]
[go-captcha-angular](https://github.com/wikylyu/go-captcha-angular)

![截图](https://raw.githubusercontent.com/wikylyu/go-captcha-angular/master/screenshot/Screenshot.png)

我觉得可以增加到README中。

**Comment by wenlng** [comment]
> [go-captcha-angular](https://github.com/wikylyu/go-captcha-angular)
> 
> ![截图](https://raw.githubusercontent.com/wikylyu/go-captcha-angular/master/screenshot/Screenshot.png)
> 
> 我觉得可以增加到README中。

v2准备发布了，你会持续更新吗

**Comment by wikylyu** [comment]
> 持续

后续有时间我会更新，现在先把这个issue关闭吧，毕竟我上次更新这个已经隔了好几个angular版本了。
