### ISSUE TITLE
文档再完善些，示例再精简些

### ISSUE THREAD

**Issue by zhangbest5** [wenlng/go-captcha#7]
大神好，这个项目达到了我想要的效果，很强大
但，文档太不友好了。。。（自学go一年多，表示完全上不了手）
给的go_captcha_demo（https://github.com/wenlng/go-captcha-example）
也和文档基本对不上啊

希望大神可以做成开箱即用的那种,js抽离出来，页面简洁些，验证码的生成、验证、以及缓存明确下。。。。

**Comment by wenlng** [comment]
> 大神好，这个项目达到了我想要的效果，很强大 但，文档太不友好了。。。（自学go一年多，表示完全上不了手） 给的go_captcha_demo（[https://github.com/wenlng/go-captcha-example）](https://github.com/wenlng/go-captcha-example%EF%BC%89) 也和文档基本对不上啊
> 
> 希望大神可以做成开箱即用的那种,js抽离出来，页面简洁些，验证码的生成、验证、以及缓存明确下。。。。

v2 版本已重构，会是极简的使用方式，即将发布
